### ISSUE TITLE
Health check for Directus docker container fails

### ISSUE THREAD

**Issue by langiole** [citrineos/citrineos-core#101]
The output of the `docker compose up` command indicates that the directus container did no start up successfully:

<img width="650" alt="Screenshot 2024-05-21 at 18 52 12" src="https://github.com/citrineos/citrineos-core/assets/14906622/e6a77628-ed65-4754-9f09-3fa525677bfa">

But docker desktop shows that the container is running:
<img width="401" alt="Screenshot 2024-05-21 at 18 52 23" src="https://github.com/citrineos/citrineos-core/assets/14906622/fd2a44df-5312-45ea-a259-6b6800f2597e">

So, perhaps health check failed for this container.

This prevents the citrine container from starting.

**Comment by DiegoLelis** [comment]
Advice from a newbie here that just found Citrine, so take it with a grain of salt lol.
Depending on your OS, Docker-desktop has some problems connecting the container ports to your host ports, so it could show that it is running but it was just not able to bind to the host port.
Checking if you have anything running on that port could solve the issue.

I've also noticed that they've did some updates over the last hours, I just run this on Ubuntu ```VERSION="22.04.2 LTS (Jammy Jellyfish)"```, and it worked.

Here is my Docker version: ```Docker version 24.0.2, build cb74dfc```
I don't run docker-desktop, I install all the docker components separately, so your equivalent version will probably be different, but somewhere hidden in docker-desktop you can find those.

Hope the easiest path works: Just download the latest

**Comment by thanaParis** [comment]
To add to the above, the Directus container can sometimes fail health checks and still be running, often when Directus has issues connecting to the database. The database will likely need to be restarted. Once the database is healthy (check by looking at the logs and making sure there's a log saying it's ready to accept connections), restart the Directus container then the Citrine container.

If this doesn't help, posting the logs of the Directus container would let me see if I can diagnose the issue further.
