### ISSUE TITLE
Question about load balancing

### ISSUE THREAD

**Issue by DiegoLelis** [citrineos/citrineos-core#102]
Heyyy, so, really sorry about the possible dumb question.

But I've just found Citrine and I'm considering to use on a project.

I was looking through the interface/docs, and I'm not sure if it would be possible to do loadbalancing between chargers, I can see the module: 03_Modules/SmartCharging, but I was not able to find any configuration on the interface/api to set that.

Maybe this is done on the Charger side with OCPP or when I'm setting up a new charger?

I'm kind of new to the OCPP ecosystem, so sorry if my question is too dumb :-).

**Comment by ChrisWeissmann** [comment]
Hi @DiegoLelis , 
we have generated the API interfaces, and you can send charging profiles down the wire. (Call the API endpoint with what you want to push to the charger) But we haven't added any logic on citrine side to do load balancing part. It's on the roadmap for the future though.

**Comment by thanaParis** [comment]
As Chris said, at the moment there's no automatic load balancing feature on CitrineOS.

Load balancing often doesn't need to be handled by the CSMS however; many charging stations handle it themselves. May I ask what sort of project you are intending to use CitrineOS in?

**Comment by DiegoLelis** [comment]
I'm looking into installing EV charging infrastructure into my building (34 parking spots), and considering to deploy Citrine to allow me to use OCPP charging stations.

**Comment by DiegoLelis** [comment]
Could you point me to a few charging stations (North America, Canada) that handle the load balancing themselves?

**Comment by DiegoLelis** [comment]
Thank you so much!
