### ISSUE TITLE
Having issues with secure websocket connection

### ISSUE THREAD

**Issue by Naveensparks** [citrineos/citrineos-core#83]
I have a SECC which supports OCPP 1.6J and 2.0.1 with most of the profiles.
I built my own test cases with simple if else / switch cases. There I was able to handle my certificates well.
I was able to simple throw the key.pem and cert.pem directly into the code (self-signed).
But here, I don't know and can't figure out how to establish a wss:// connection with critineOS from my SECC . I tried with various methods which usually we do in testing but in vain.

I know this is a simple question, yet It will be great if someone can help me with this.

**Comment by thanaParis** [comment]
Hi @Naveensparks ! CitrineOS supports security profiles 2 and 3 by way of our SystemConfiguration. In `Server/src/config/env` you can see some examples of these configuration files. In `00_Base/src/config/types.ts` you can find the schema used to define the websocket servers CitrineOS spins up. This includes file paths for server keys and certificate chains for tls as well as Certificate Authority files for mtls, both of which use wss.
If you modify the docker.ts file in Server to include a websocket server with security profile 2 or 3, and provide the needed PKI files, you will be able to connect to that server's port using wss once CitrineOS starts up. Note you still need an auth header for security profile 2.

This system is being overhauled in the current release candidate, to be able to support external CAs better and more easily regenerate certificates.

**Comment by Naveensparks** [comment]
Thanks, it worked.
